### ISSUE TITLE
IntelliJ doesn't properly resolve dependencies with Gradle 4.8 and this plugin

### ISSUE THREAD

**Issue by vpavic** [spring-gradle-plugins/spring-build-conventions#28]
With Gradle 4.8, IntelliJ doesn't properly resolve dependencies for a module that relies on this plugin (namely `io.spring.convention.spring-test`) and declares only `testCompile` dependencies. The net result of this is that the project can't be compiled in IDE.

This behavior can be reproduced using [Spring Session](https://github.com/spring-projects/spring-session), where [`docs` module](https://github.com/spring-projects/spring-session/blob/master/docs/spring-session-docs.gradle) declares the following dependencies:

```
dependencies {
	testCompile project(':spring-session-core')
	testCompile project(':spring-session-data-redis')
	testCompile project(':spring-session-hazelcast')
	testCompile project(':spring-session-jdbc')
	testCompile 'org.springframework:spring-jdbc'
	testCompile 'org.springframework:spring-messaging'
	testCompile 'org.springframework:spring-webmvc'
	testCompile 'org.springframework:spring-websocket'
	testCompile 'org.springframework.security:spring-security-config'
	testCompile 'org.springframework.security:spring-security-web'
	testCompile 'org.springframework.security:spring-security-test'
	testCompile 'junit:junit'
	testCompile 'org.mockito:mockito-core'
	testCompile 'org.springframework:spring-test'
	testCompile 'org.assertj:assertj-core'
	testCompile 'com.hazelcast:hazelcast'
	testCompile 'io.lettuce:lettuce-core'
	testCompile 'javax.servlet:javax.servlet-api'
}
```

With Gradle 4.7 (project at commit spring-projects/spring-session@63f1050) this is resolved as expected:

![gradle-4 7](https://user-images.githubusercontent.com/1149230/41335804-61bee1e2-6eea-11e8-82db-c26903bc0a31.png)

However with Gradle 4.8 (project at commit spring-projects/spring-session@4a52de0) this is resolved as:

![gradle-4 8](https://user-images.githubusercontent.com/1149230/41335848-8a130d9e-6eea-11e8-9726-d3fe274909dd.png)

Which results in compilation errors. If however a single dependency is declared as `compile` dependency, then things do work with 4.8:

![gradle-4 8-workaround](https://user-images.githubusercontent.com/1149230/41335913-c8713e4e-6eea-11e8-87ee-f696324c4aa1.png)

I've tracked the root cause to use of `propdeps-idea` - with that plugin out of the picture, the dependencies are resolved as expected. Perhaps we could consider replacing the `propdeps-plugin` with `gradle-extra-configurations-plugin`?
